server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ai-service
          uri: http://localhost:8081
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
        
        - id: devops-service
          uri: http://localhost:8082
          predicates:
            - Path=/devops/**
          filters:
            - StripPrefix=1
        
        - id: security-service
          uri: http://localhost:8083
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG