name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: karun45
          password: nuraK@1234
      
      # Build and push devops-service
      - name: Build and push devops-service
        uses: docker/build-push-action@v2
        with:
          context: ./devops-service
          push: true
          tags: karun45/devops-service:latest
      
      # Build and push security-service
      - name: Build and push security-service
        uses: docker/build-push-action@v2
        with:
          context: ./security-service
          push: true
          tags: karun45/security-service:latest
      
      # Build and push ai-service
      - name: Build and push ai-service
        uses: docker/build-push-action@v2
        with:
          context: ./ai-service
          push: true
          tags: karun45/ai-service:latest
      
      # Build and push api-gateway
      - name: Build and push api-gateway
        uses: docker/build-push-action@v2
        with:
          context: ./api-gateway
          push: true
          tags: karun45/api-gateway:latest
      
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          kubectl apply -f k8s/